# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://xensakura.dev'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

# Title of the Site
title: Sakura Shih
# Description of the Site
description: Game Development Software Engineer
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: contact@xensakura.dev
facebook_username: 
twitter_username: shih_sakura
instagram_username:
linkedin_username: xensakura
github_username:  XenSakura
youtube_channel_id: UCQe7H4VjxxCrX1_Xg6ny2kw
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 31q4cisl6jsd3pugm7s4t3lwjd54

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: sakurashih

# Name of the Author
author-name: Sakura Shih
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Entry-level Game Development Software Engineer that demonstrates a commitment to leadership and collaborative work environments, looking to join a world-class studio and work on innovative game development technology. Leverages skills in low-level programming, interdisciplinary collaborative experience, and an initiative to learn.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/XenSakura

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
